name: Release New Version

on:
  push:
    branches: [master]
    paths:
      - src/**/*.py
      - tests/**/*.py
      - tools/**/*.py
      - pyproject.toml
  workflow_dispatch:

jobs:
  preflight-check:
    uses: ./.github/workflows/test.yml

  taxi:
    needs: preflight-check
    runs-on: ubuntu-latest
    # trunk-ignore(checkov/CKV2_GHA_1)
    permissions:
      contents: write # For pushing tag, commit and creating release
      id-token: write # Needed for downstream publish workflow

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for bumpver

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Bump version
        id: bumpver
        run: |
          uv run --frozen bumpver update --commit --tag-commit
          NEW_VERSION=$(grep -m1 'current_version = ' pyproject.toml | cut -d'"' -f2)
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Tag and push
        run: |
          git push
          git push origin ${{ steps.bumpver.outputs.version }}

  takeoff:
    needs: taxi
    uses: ./.github/workflows/publish.yml
