name: Release New Version

on:
  push:
    branches: [master]
    paths:
      - "src/**/*.py"
      - "tests/**/*.py"
      - "tools/**/*.py"
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  preflight-check:
    uses: ./.github/workflows/test.yml

  release:
    needs: preflight-check
    runs-on: ubuntu-latest
    permissions:
      contents: write # For pushing tag, commit and creating release

    # Only run if push is from a human (not another workflow, to avoid loops on tag push)
    if: github.actor != 'actions-user'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for bumpver

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Bump version
        id: bumpver
        run: |
          uv run --frozen bumpver update --commit --tag-commit
          # Extract the new version
          NEW_VERSION="$(grep -m1 'current_version = ' pyproject.toml | cut -d'"' -f2)"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Tag and push
        run: |
          git push
          git push origin ${{ steps.bumpver.outputs.version }}
